// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeIE4sVuJmtesSV6RG8rfuNCejI6mVM_8',
    appId: '1:898940737671:web:414c4321cd230c8d530022',
    messagingSenderId: '898940737671',
    projectId: 'photogallery-caee8',
    authDomain: 'photogallery-caee8.firebaseapp.com',
    storageBucket: 'photogallery-caee8.appspot.com',
    measurementId: 'G-5E60Z6KGVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbXKNAJCW41Na8nc7TulXCkN-_ho3kZyo',
    appId: '1:898940737671:android:e596ef79a7fe42aa530022',
    messagingSenderId: '898940737671',
    projectId: 'photogallery-caee8',
    storageBucket: 'photogallery-caee8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPBnl9ZBPpWR0Qt72ybTWFYoDm9OxIUkw',
    appId: '1:898940737671:ios:aa8e1e20e6a00e47530022',
    messagingSenderId: '898940737671',
    projectId: 'photogallery-caee8',
    storageBucket: 'photogallery-caee8.appspot.com',
    iosClientId: '898940737671-17j412d3ftomng83ah33thg8ctukoal7.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoGallery',
  );
}
